name = "lavanderiasandra"

compatibility_date = "2025-12-25"

compatibility_flags = [
  "nodejs_compat",
  "nodejs_als"
]

pages_build_output_dir = ".svelte-kit/cloudflare"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "lavanderia"
database_id = "0cf1e191-717c-4231-a5b9-e472a4c9d8c1"
preview_database_id = "local"

