CREATE TABLE departures (
  departure_id INTEGER PRIMARY KEY AUTOINCREMENT,
  laundry_id INTEGER DEFAULT 0,
  invoice_id INTEGER DEFAULT 0,
  admin_id INTEGER DEFAULT 0,
  exit_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
